### ISSUE TITLE
Passing undefined as parameter to log causes an exception

### ISSUE THREAD

**Issue by anwarhamr** [olofd/react-native-device-log#10]
log.info("some message", undefined); seems to be the issue.  
I have a fix that I will make a pull request.

**Comment by olofd** [comment]
Did this resolve with your last PR? Closing. Reopen if it's still an issue.

**Comment by anwarhamr** [comment]
Thanks for the quick response!  If you included 2 pull requests for me
fix-issue-10 and fix-issue-12 you''re good.  Again, thanks for the package!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Cheers,
Rob Lingstuyl
Software (Programmer & Architect)
+1 801 599-1596
808numbers@gmail.com
http://www.linkedin.com/in/robertl

*Somebody should tell us, right at the start of our lives, that we are
dying. Then we might live life to the limit, every minute of every day. Do
it! I say. Whatever you want to do, do it now! There are only so many
tomorrows.* ~ Pope Paul VI
