### ISSUE TITLE
Super express must either be null or a function, not undefined

### ISSUE THREAD

**Issue by bestofsong** [olofd/react-native-device-log#2]
relevant code: 

```
import React, { Component } from 'react';
import deviceLog, {LogView} from 'react-native-device-log';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  AsyncStorage,
} from 'react-native';

deviceLog.init(AsyncStorage, { logToConsole : true }).then(() => {
  //When the deviceLog has been initialized we can clear it if we want to:
  //deviceLog.clear();
});
```

and i debug and found the single line 

```
import deviceLog, {LogView} from 'react-native-device-log';
```

caused the exception

Maybe it's the version issue:?

node -v

> v6.2.0

react-native --version

> react-native-cli: 0.2.0
> react-native: 0.26.0

version of this repo:
"react-native-device-log": "0.0.7"

Nice log utility if it could work, please fix it!

**Comment by olofd** [comment]
Sry for extremely slow fix. But test it now. I think it will work. Otherwise. post here and I'll reopen.
