### ISSUE TITLE
keyboardShouldPersistTaps={true/false} is deprecated

### ISSUE THREAD

**Issue by antseburova** [olofd/react-native-device-log#5]
Hi,

I upgraded to React Native 0.40.0 and got the following warning:

![image](https://cloud.githubusercontent.com/assets/5235176/22623042/38283bca-eb1b-11e6-9b08-6130f40619d2.png)

I know it is not a big deal, but it would be nice to get rid of that warning. It seems like an easy fix. 

Please let me know if you have any questions.

Thank you

**Comment by olofd** [comment]
fixed in version 0.0.16 on npm.

**Comment by antseburova** [comment]
Thank you very much!
