### ISSUE TITLE
Add plus attribute to stored object

### ISSUE THREAD

**Issue by Xyzor** [olofd/react-native-device-log#8]
Hello!

First of all, thanks to sharing this package.
I'm planning to use it in an app to store user activities and errors.
I'd like to send the stored logs back to the server. Because the app works offline too, i have to be able to label the logs which failed to get back to the server or happened offline.

Do you think  that is a good feature to be able to bind data to the log?
Something like this:
`deviceLog.info('Order failed', { forwarded: { false } })`

If so, I can try to make a PR for this.

**Comment by olofd** [comment]
Hi!
Thanks for using the package. An idea is to use a custom adapter for you messages.
As you see in the README.me:

```
deviceLog.init(AsyncStorage /* You can send new InMemoryAdapter() if you do not want to persist here*/
,{
  //Options (all optional):
  logToConsole : false, //Send logs to console as well as device-log
  logRNErrors : true, // Will pick up RN-errors and send them to the device log
  maxNumberToRender : 2000, // 0 or undefined == unlimited
  maxNumberToPersist : 2000 // 0 or undefined == unlimited
}).then(()
```

See there that I pass AsyncStorage as the API that device-log should use?
You could just as easily pass your own adapter that implements the same API as AsyncStorage:
eg. get, set, remove etc. In this adapter you would Save the massages to AsyncStorage but also send them to your server. In here you can denote the message, if it's sent or not in any way you like.

This way you could easily write this entire functionality without needing to update this library.
Does it make sense?

Let me know if you need help in your way or if anything does not work as expected.

Olof

**Comment by olofd** [comment]
FYI. I have an custom InMemory-adapter included in the library, you can look at it if you need to now what methods needs to be implemented:

https://github.com/olofd/react-native-device-log/blob/master/adapters/in-memory.js

**Comment by Xyzor** [comment]
Thanks for the fast reply.

I'll definitely give it a try and give some feedback here.

**Comment by Xyzor** [comment]
I have modified your fallback adapter but i can't make the AsyncStorage to save the log.

Here is a snack example: https://snack.expo.io/r1eDwJ2YZ

**Comment by olofd** [comment]
A rewrite of some internals are in the making for this feature. Hang in there:
https://github.com/olofd/react-native-device-log/commit/c272f60ce67e5f597bcc952828b47af6d1ae4e3a

**Comment by olofd** [comment]
So I've added the functionality to version 1.0. This i my code for using it. But also, look though the code and copy to your own DataWriter if you want to customize.

```
deviceLog
            .init(
                null /* You can send new InMemoryAdapter() if you do not want to persist here*/,
                {
                    //Options (all optional):
                    customDataWriter: new StorageServerHocWriter(
                        new StringifyDataWriter(AsyncStorage),
                        {
                            batchSize: 100,
                            sendInterval: 45000,
                            skipSendingMessagesOlderThen: moment().subtract(
                                3,
                                "days"
                            ),
                            getExtraData: () => {
                                return { ...extraData };
                            },
                            modifyRowBeforeSend: logRow => {
                                const newLogRow = { ...logRow };
                                delete newLogRow.color;
                                return newLogRow;
                            },
                            serverUrl: `${serverUrl}api/clientlog`,
                            isDebug: __DEV__,
                            sendLevels: ["all"],
                        }
                    ),
                    logToConsole: true, //Send logs to console as well as device-log
                    logRNErrors: true, // Will pick up RN-errors and send them to the device log
                    maxNumberToRender: 1000, // 0 or undefined == unlimited
                    maxNumberToPersist: 1000, // 0 or undefined == unlimited
                    disableLevelToConsole: ["debug"],
                }
            )
            .then(logger => {
                console.log("Logger has started");
                //deviceLog.clear();
                return this;
            });
```

**Comment by Xyzor** [comment]
Thanks @olofd 

You surprised me, I didn't expect this much help. :open_mouth:
It looks realy good, unfortunately I won't be able to work on this until the weekend.

**Comment by olofd** [comment]
👍 No problems. I needed this function as well. So it aligned well.

**Comment by olofd** [comment]
Closing.
