### ISSUE TITLE
The type is undefined

### ISSUE THREAD

**Issue by 445560292** [olofd/react-native-device-log#9]
NetInfo.addEventListener(
            "connectionChange",
            this._handleConnectivityTypeChange.bind(this)
        );
 _handleConnectivityTypeChange(connectionInfo) {
        let { type, effectiveType } = connectionInfo;
        if (type === "none") {
            this.hasBeenDisconnected = true;
            this.seperator(`DISCONNECTED FROM INTERNET`);
        } else {
            const buildConnectionString = () => {
                return `${type.toUpperCase()}${effectiveType === "unknown"
                    ? ""
                    : ` - ${effectiveType}`}`;
            };
            if (this.hasBeenDisconnected) {
                this.seperator(
                    `[NETINFO] RECONNECTED TO ${buildConnectionString()}`
                );
            } else {
                if (this.connectionHasBeenEstablished) {
                    this.seperator(
                        `[NETINFO] CHANGED TO ${buildConnectionString()}`
                    );
                } else {
                    this.seperator(
                        `[NETINFO] CONNECTION TO ${buildConnectionString()}`
                    );
                }
            }
        }
        this.connectionHasBeenEstablished = true;
    }

Hi olofd, These code is in debug-service.js and connectionInfo is just a string like 'wifi'.

Here is my environemnt:

System
  platform           darwin
  arch               x64
  cpu                4 cores                                     Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
  directory          /Users/hank/Documents/workspace/steps-app

JavaScript
  node               8.1.3        /usr/local/bin/node
  npm                5.0.3        /usr/local/bin/npm
  yarn               0.18.1       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.46.4

Ignite
  ignite             2.0.0        /usr/local/bin/ignite

Android
  java               1.8.0_31     /usr/bin/java
  android home       -            undefined

iOS
  xcode              8.3.3

Can you help us to look at this bug? 

Thanks,
Hank

**Comment by olofd** [comment]
The problem is ```app rn version 0.46.4```
You need to update you RN-dependency. Try it on 0.48.
I'll reopen if it's still an issue.
